# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dictionary(object):
	def setupUi(self, Dictionary):
		Dictionary.setObjectName("Dictionary")
		Dictionary.resize(604, 314)
		self.centralwidget = QtWidgets.QWidget(Dictionary)
		self.centralwidget.setObjectName("centralwidget")
		self.searchText = QtWidgets.QLineEdit(self.centralwidget)
		self.searchText.setGeometry(QtCore.QRect(130, 40, 161, 41))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.searchText.setFont(font)
		self.searchText.setText("")
		self.searchText.setObjectName("searchText")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(20, 40, 101, 31))
		self.label.setObjectName("label")
		self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
		self.textBrowser.setGeometry(QtCore.QRect(130, 130, 161, 111))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.textBrowser.setFont(font)
		self.textBrowser.setObjectName("textBrowser")
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(30, 170, 81, 31))
		self.label_2.setObjectName("label_2")
		self.searchButton = QtWidgets.QPushButton(self.centralwidget)
		self.searchButton.setGeometry(QtCore.QRect(160, 90, 93, 28))
		self.searchButton.setObjectName("searchButton")
		self.addButton = QtWidgets.QPushButton(self.centralwidget)
		self.addButton.setGeometry(QtCore.QRect(420, 100, 93, 28))
		self.addButton.setObjectName("addButton")
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(350, 50, 72, 15))
		self.label_3.setObjectName("label_3")
		self.chText = QtWidgets.QLineEdit(self.centralwidget)
		self.chText.setGeometry(QtCore.QRect(400, 40, 141, 41))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.chText.setFont(font)
		self.chText.setObjectName("chText")
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(350, 160, 41, 16))
		self.label_4.setObjectName("label_4")
		self.enText = QtWidgets.QLineEdit(self.centralwidget)
		self.enText.setGeometry(QtCore.QRect(400, 160, 141, 41))
		font = QtGui.QFont()
		font.setPointSize(16)
		self.enText.setFont(font)
		self.enText.setObjectName("enText")
		Dictionary.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(Dictionary)
		self.statusbar.setObjectName("statusbar")
		Dictionary.setStatusBar(self.statusbar)

		self.retranslateUi(Dictionary)
		QtCore.QMetaObject.connectSlotsByName(Dictionary)

	def retranslateUi(self, Dictionary):
		_translate = QtCore.QCoreApplication.translate
		Dictionary.setWindowTitle(_translate("Dictionary", "Dictionary"))
		self.label.setText(_translate("Dictionary", "输入单词/中文"))
		self.label_2.setText(_translate("Dictionary", "搜索结果:"))
		self.searchButton.setText(_translate("Dictionary", "搜索"))
		self.addButton.setText(_translate("Dictionary", "添加单词"))
		self.label_3.setText(_translate("Dictionary", "中文"))
		self.label_4.setText(_translate("Dictionary", "英文"))
