# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.registry = QtWidgets.QPushButton(self.centralwidget)
        self.registry.setGeometry(QtCore.QRect(40, 170, 91, 31))
        self.registry.setObjectName("registry")
        self.control = QtWidgets.QPushButton(self.centralwidget)
        self.control.setGeometry(QtCore.QRect(140, 170, 111, 31))
        self.control.setObjectName("control")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(40, 30, 261, 31))
        self.search.setObjectName("search")
        self.exec = QtWidgets.QPushButton(self.centralwidget)
        self.exec.setGeometry(QtCore.QRect(310, 30, 71, 31))
        self.exec.setObjectName("exec")
        self.dev = QtWidgets.QPushButton(self.centralwidget)
        self.dev.setGeometry(QtCore.QRect(260, 220, 121, 31))
        self.dev.setObjectName("dev")
        self.disk = QtWidgets.QPushButton(self.centralwidget)
        self.disk.setGeometry(QtCore.QRect(260, 170, 121, 31))
        self.disk.setObjectName("disk")
        self.command = QtWidgets.QPushButton(self.centralwidget)
        self.command.setGeometry(QtCore.QRect(40, 220, 91, 31))
        self.command.setObjectName("command")
        self.server = QtWidgets.QPushButton(self.centralwidget)
        self.server.setGeometry(QtCore.QRect(140, 220, 111, 31))
        self.server.setObjectName("server")
        self.result = QtWidgets.QListView(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(40, 70, 341, 81))
        self.result.setObjectName("result")
        self.check_folder = QtWidgets.QPushButton(self.centralwidget)
        self.check_folder.setGeometry(QtCore.QRect(140, 300, 111, 31))
        self.check_folder.setObjectName("check_folder")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 300, 91, 31))
        self.label.setObjectName("label")
        self.floder = QtWidgets.QLabel(self.centralwidget)
        self.floder.setGeometry(QtCore.QRect(270, 300, 141, 31))
        self.floder.setObjectName("floder")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(40, 350, 131, 31))
        self.filename.setObjectName("filename")
        self.renamebtn = QtWidgets.QPushButton(self.centralwidget)
        self.renamebtn.setGeometry(QtCore.QRect(200, 350, 111, 31))
        self.renamebtn.setObjectName("renamebtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registry.setText(_translate("MainWindow", "打开注册表"))
        self.control.setText(_translate("MainWindow", "打开控制面板"))
        self.exec.setText(_translate("MainWindow", "Search"))
        self.dev.setText(_translate("MainWindow", "打开设备管理器"))
        self.disk.setText(_translate("MainWindow", "打开磁盘管理器"))
        self.command.setText(_translate("MainWindow", "打开CMD"))
        self.server.setText(_translate("MainWindow", "打开本地服务"))
        self.check_folder.setText(_translate("MainWindow", "选择文件夹"))
        self.label.setText(_translate("MainWindow", "文件批量重命名"))
        self.floder.setText(_translate("MainWindow", "未选择文件夹"))
        self.renamebtn.setText(_translate("MainWindow", "重命名"))
